version: "3"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    command: npm run start:dev
    restart: unless-stopped
    networks:
      - branch-network

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    logging:
      driver: none
    networks:
      - branch-network

networks:
  branch-network:
    driver: bridge
