### Create Company
POST {{URL}}/company/onboarding
Content-Type: application/json

{
    "website": "https://babatraders.in",
    "phone": "9090974785",
    "countryCode": "+91",
  "name": "Baba Traders"
}

### Get career page
// @no-log
GET {{URL}}/company/65959cab7e25e8b1e5087281
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}
