### Create a job
// @no-log
POST {{URL}}/jobs
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

{
  "title": "Full-stack developer-2",
  "description": "Complete developer that can handle any thing.",
  "locationType": "REMOTE",
  "location": "Delhi",
  "company": "65959cab7e25e8b1e5087281",
  "employmentType": "Full-time",
  "experience": "5+"
}


### Fetch all jobs
// @no-log
GET {{URL}}/jobs/all
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}

### Fetch active jobs only
// @no-log
GET {{URL}}/jobs
Content-Type: application/json
Authorization: Bearer {{AUTH_TOKEN}}
