### Create User against company
POST {{URL}}/users/create
Content-Type: application/json

{
  "email": "imabg@bt.in",
  "name": "Abhay Goswami",
  "company": "65959cab7e25e8b1e5087281"
}

### Update password
POST {{URL}}/users/update/password
Content-Type: application/json

{
  "password": "Password123#",
  "userId": "65959d157e25e8b1e5087283"
}
